CREATE TABLE ESPECIALIDADE(
    ID INTEGER IDENTITY,
    NOME VARCHAR(250) NOT NULL
);

CREATE TABLE MEDICO(
    ID INTEGER IDENTITY,
    NOME VARCHAR(250) NOT NULL,
    CPF VARCHAR(15) NOT NULL,
    CRM VARCHAR(15) NOT NULL,
    ESPECIALIDADE INTEGER NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
    ENDERECO VARCHAR(100) NOT NULL,
    SEXO VARCHAR(1),
    FOREIGN KEY (ESPECIALIDADE) REFERENCES ESPECIALIDADE(ID)
);

CREATE TABLE PACIENTE(
    ID INTEGER IDENTITY,
    NOME VARCHAR(250) NOT NULL,
    CPF VARCHAR(15) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
    ENDERECO VARCHAR(250) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    SEXO VARCHAR(1)
);

CREATE TABLE USUARIO(
    ID INTEGER IDENTITY,
    LOGIN VARCHAR(50) NOT NULL,
    SENHA VARCHAR(32) NOT NULL
);

CREATE TABLE CONSULTA(
    ID INTEGER IDENTITY,
    DATA DATE NOT NULL,
    HORARIO TIME NOT NULL,
    MEDICO INTEGER NOT NULL,
    PACIENTE INTEGER NOT NULL,
    OBSERVACAO VARCHAR(500) NOT NULL,
    FOREIGN KEY (MEDICO) REFERENCES MEDICO(ID),
    FOREIGN KEY (PACIENTE) REFERENCES PACIENTE(ID)
);
